export const LOGGEDIN = 'LOGGEDIN';
export const LOGGEDOUT = 'LOGGEDOUT';
export const UPDATE_USER = 'UPDATE_USER';

export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const UPDATE_SPOT = 'UPDATE_SPOT';

export const UPDATE_MINE_STORIES = 'UPDATE_MINE_STORIES';
export const UPDATE_STORIES = 'UPDATE_STORIES';
export const UPDATE_CHATS = 'UPDATE_CHATS';

export const UPDATE_FOLLOWERS = 'UPDATE_FOLLOWERS';
export const UPDATE_FOLLOWINGS = 'UPDATE_FOLLOWINGS';
export const UPDATE_OTHER_FOLLOWERS = 'UPDATE_OTHER_FOLLOWERS';
export const UPDATE_OTHER_FOLLOWINGS = 'UPDATE_OTHER_FOLLOWINGS';
